window.env = {
  TAG_URL: ENV_TAG_URL,
  WEB_SDK_URL: ENV_WEB_SDK_URL,
  WEB_SDK_CTV_URL: ENV_WEB_SDK_CTV_URL,
  TP_URL: ENV_TP_URL,
  TOUCHPOINT_URL: ENV_TOUCHPOINT_URL,
  SUI_CONNECTOR_URL: ENV_SUI_CONNECTOR_URL,
  EXTENSION_BASE_URL: ENV_EXTENSION_BASE_URL
};
